const franceData = {
    regions: [
        {
            id: 'gironde',
            name: 'Gironde (33)',
            coordinates: { latitude: 44.84, longitude: -0.58 },
            adminRegion: 'Nouvelle-Aquitaine',
            keyAppellations: 'Bordeaux, Bordeaux Supérieur, Médoc, Saint-Émilion, Côtes de Bourg',
            programPhase: 'Phase 1 (2023) + Phase 2 (2024)',
            hectaresApplied: 7812,
            hectaresPermanent: 3600,
            hectaresPartial: 4212,
            growersApplied: 1020,
            fullExitGrowers: 277,
            compensationRate: 6000,
            estimatedCompensation: 46.9,
            earliestReplantDate: '2029',
            dominantWineType: 'Red AOP (65%)',
            notes: '27% of Gironde applicants seek full exit. Largest program by hectares. Bordeaux AOP land prices fell ~30% in decade prior to 2022. Phase 1: 20-year replant ban.'
        },
        {
            id: 'aude',
            name: 'Aude (11)',
            coordinates: { latitude: 43.21, longitude: 2.35 },
            adminRegion: 'Occitanie',
            keyAppellations: 'Minervois, Corbières, Fitou, Vin de France IGP',
            programPhase: 'Phase 2 (2024)',
            hectaresApplied: 4470,
            hectaresPermanent: 1430,
            hectaresPartial: 3040,
            growersApplied: 610,
            fullExitGrowers: 162,
            compensationRate: 4000,
            estimatedCompensation: 17.9,
            earliestReplantDate: '2029',
            dominantWineType: 'Red IGP/AOP',
            notes: '16% of Phase 3 applications. Wildfire risk noted in uprooted areas (2025). Worst wildfire in Aude in 70 years partly due to reduced vine density.'
        },
        {
            id: 'gard',
            name: 'Gard (30)',
            coordinates: { latitude: 43.84, longitude: 4.36 },
            adminRegion: 'Occitanie',
            keyAppellations: 'Costières de Nîmes, Côtes du Rhône, Clairette de Bellegarde',
            programPhase: 'Phase 2 (2024)',
            hectaresApplied: 3350,
            hectaresPermanent: 1070,
            hectaresPartial: 2280,
            growersApplied: 460,
            fullExitGrowers: 122,
            compensationRate: 4000,
            estimatedCompensation: 13.4,
            earliestReplantDate: '2029',
            dominantWineType: 'Red (Côtes du Rhône)',
            notes: '12% of Phase 3 applications. Significant Côtes du Rhône volume removed. Part of Occitanie region representing >50% of national surfaces.'
        },
        {
            id: 'herault',
            name: 'Hérault (34)',
            coordinates: { latitude: 43.61, longitude: 3.88 },
            adminRegion: 'Occitanie',
            keyAppellations: 'Languedoc AOP, Picpoul de Pinet, Saint-Chinian, Faugères',
            programPhase: 'Phase 2 (2024)',
            hectaresApplied: 2790,
            hectaresPermanent: 892,
            hectaresPartial: 1898,
            growersApplied: 380,
            fullExitGrowers: 101,
            compensationRate: 4000,
            estimatedCompensation: 11.2,
            earliestReplantDate: '2029',
            dominantWineType: 'Red & Rosé AOP',
            notes: '10% of Phase 3 applications. Picpoul (white) largely excluded. Languedoc region significant volume in overall program.'
        },
        {
            id: 'pyr-orientales',
            name: 'Pyrénées-Orientales (66)',
            coordinates: { latitude: 42.70, longitude: 2.89 },
            adminRegion: 'Occitanie',
            keyAppellations: 'Côtes du Roussillon, Muscat de Rivesaltes, Banyuls',
            programPhase: 'Phase 2 (2024)',
            hectaresApplied: 1960,
            hectaresPermanent: 627,
            hectaresPartial: 1333,
            growersApplied: 268,
            fullExitGrowers: 71,
            compensationRate: 4000,
            estimatedCompensation: 7.8,
            earliestReplantDate: '2029',
            dominantWineType: 'Red & Fortified',
            notes: '7% of Phase 3 applications. Fortified wine market in long-term decline. Focus on market stabilization.'
        },
        {
            id: 'gers',
            name: 'Gers (32)',
            coordinates: { latitude: 43.65, longitude: 0.59 },
            adminRegion: 'Occitanie / Sud-Ouest',
            keyAppellations: 'Armagnac, Côtes de Gascogne IGP, Madiran',
            programPhase: 'Phase 2 (2024)',
            hectaresApplied: 1120,
            hectaresPermanent: 504,
            hectaresPartial: 616,
            growersApplied: 153,
            fullExitGrowers: 51,
            compensationRate: 4000,
            estimatedCompensation: 4.5,
            earliestReplantDate: '2029',
            dominantWineType: 'White (Armagnac)',
            notes: '4% of Phase 3 applications. 33% full exit rate — highest nationally. Aging grower demographics significant factor.'
        },
        {
            id: 'vaucluse',
            name: 'Vaucluse (84)',
            coordinates: { latitude: 44.00, longitude: 5.05 },
            adminRegion: 'Provence-Alpes-Côte d\'Azur',
            keyAppellations: 'Côtes du Rhône, Ventoux, Luberon, Châteauneuf-du-Pape vicinity',
            programPhase: 'Phase 2 (2024)',
            hectaresApplied: 840,
            hectaresPermanent: 269,
            hectaresPartial: 571,
            growersApplied: 115,
            fullExitGrowers: 31,
            compensationRate: 4000,
            estimatedCompensation: 3.4,
            earliestReplantDate: '2029',
            dominantWineType: 'Red AOP',
            notes: '3% of Phase 3 applications. Near Châteauneuf-du-Pape; quality reds under price pressure.'
        },
        {
            id: 'tarn',
            name: 'Tarn (81)',
            coordinates: { latitude: 43.93, longitude: 2.14 },
            adminRegion: 'Occitanie',
            keyAppellations: 'Gaillac, Côtes du Tarn IGP',
            programPhase: 'Phase 2 (2024)',
            hectaresApplied: 560,
            hectaresPermanent: 179,
            hectaresPartial: 381,
            growersApplied: 77,
            fullExitGrowers: 20,
            compensationRate: 4000,
            estimatedCompensation: 2.2,
            earliestReplantDate: '2029',
            dominantWineType: 'Red & White',
            notes: '2% of Phase 3 applications. Smaller volume; structural issues in region.'
        },
        {
            id: 'drome',
            name: 'Drôme (26)',
            coordinates: { latitude: 44.73, longitude: 4.90 },
            adminRegion: 'Auvergne-Rhône-Alpes',
            keyAppellations: 'Côtes du Rhône, Crozes-Hermitage, Clairette de Die',
            programPhase: 'Phase 2 (2024)',
            hectaresApplied: 490,
            hectaresPermanent: 157,
            hectaresPartial: 333,
            growersApplied: 67,
            fullExitGrowers: 18,
            compensationRate: 4000,
            estimatedCompensation: 2.0,
            earliestReplantDate: '2029',
            dominantWineType: 'Red AOP',
            notes: 'Part of Rhône-Provence region. Côtes du Rhône quality wines under market pressure.'
        },
        {
            id: 'lot-et-garonne',
            name: 'Lot-et-Garonne (47)',
            coordinates: { latitude: 44.35, longitude: 0.62 },
            adminRegion: 'Nouvelle-Aquitaine',
            keyAppellations: 'Buzet, Côtes du Marmandais, Duras',
            programPhase: 'Phase 2 (2024)',
            hectaresApplied: 420,
            hectaresPermanent: 134,
            hectaresPartial: 286,
            growersApplied: 57,
            fullExitGrowers: 15,
            compensationRate: 4000,
            estimatedCompensation: 1.7,
            earliestReplantDate: '2029',
            dominantWineType: 'Red AOP',
            notes: 'Part of Nouvelle-Aquitaine region. Smaller appellation volumes.'
        },
        {
            id: 'charente',
            name: 'Charente / Charente-Maritime (16/17)',
            coordinates: { latitude: 45.70, longitude: -0.50 },
            adminRegion: 'Nouvelle-Aquitaine',
            keyAppellations: 'Cognac AOC (Ugni Blanc), Pineau des Charentes',
            programPhase: 'Phase 2 (2024) — Limited Eligibility',
            hectaresApplied: 963,
            hectaresPermanent: 308,
            hectaresPartial: 655,
            growersApplied: 132,
            fullExitGrowers: 35,
            compensationRate: 4000,
            estimatedCompensation: 3.9,
            earliestReplantDate: '2029',
            dominantWineType: 'Cognac (White)',
            notes: 'Limited eligibility due to AOC protection. Cognac production tied to specific regulations.'
        }
    ],
    
    nationalSummary: {
        totalHectaresApplied: 27457,
        totalHectaresPermanent: 10001,
        totalHectaresPartial: 17456,
        totalGrowersApplied: 3418,
        totalFullExitGrowers: 1001,
        totalEstimatedCompensation: 109.8,
        percentageAOP: 65,
        percentageRed: 83,
        occitaniePercentage: 50,
        programTimeline: [
            { date: 'Jan 2023', event: 'Bordeaux Phase 1 announced', budget: '€50M', target: '9,500 ha' },
            { date: 'Nov 2023', event: 'Bordeaux Phase 1 opens applications', budget: '€50M', target: '9,500 ha' },
            { date: 'Jan 2024', event: 'Bordeaux Phase 1 uprooting begins', target: '~8,000 ha' },
            { date: 'Sep 2024', event: 'National Phase 2 proposed', budget: '€120M', target: '30,000 ha' },
            { date: 'Oct 2024', event: 'EC approves Phase 2', budget: '€120M', target: '30,000 ha' },
            { date: 'Nov 2024', event: 'Phase 2 applications close', claimed: '€109.8M', actual: '27,461 ha' },
            { date: 'Jan 2026', event: 'Phase 3 conditions set', budget: '€130M', target: '~32,500 ha' },
            { date: 'Mar 2026', event: 'Phase 3 regional breakdown confirmed', actual: '27,926 ha applied' }
        ],
        marketDrivers: [
            'Declining French consumption: 120L/person/yr (1960s) → 40L/person/yr today',
            'Falling supermarket sales: −5% YoY (2024); red wine −8.5%',
            'Global oversupply: Production exceeded demand by 10% in 2023',
            'Falling exports: French wine exports −9.4% in 2023',
            'US tariff pressure: 15% US tariff on EU wines',
            'Climate & disease: 2024 record low harvest of 37–39 Mhl',
            'Aging grower demographics: 2/3 of Bordeaux growers aged >55',
            'Young consumer abstinence: Under-35s rejecting wine'
        ]
    }
};
